/* Generated from contracts.py; do not edit manually. */

import type { ActionCommand, ActionUpdatePayload, AgentBinding, AgentEventEvidence, AgentExecutionEvidence, AgentToolCallEvidence, AlertEvent, ArtifactExportCommand, ArtifactExportPayload, ArtifactExportResult, ArtifactRef, AssetOwner, AssetPermission, AssistantCommand, AssistantContextEnvelope, AssistantDiff, AssistantTurnPayload, AssistantTurnResult, Audit, AuthoringErrorCode, AuthoringEvent, AuthoringOperation, AuthoringStatus, Budget, BuildPlan, CapabilityReason, CaseCategory, CaseSource, ChartSeries, ChartViewModel, CleanRun, CleanRunRecord, CleaningRecipe, CleaningRecipeRecord, CommandResponse, CompatibilityTargets, ConnectionInstance, ConnectorCommand, ConnectorOperation, ConnectorPayload, CreateSkillDraftCommand, CreateSkillDraftPayload, DashboardKpi, DashboardViewModel, DataAccessKindSpec, DatabaseConnectorConfig, DiscoveredField, DiscoveredResource, DraftCommandResult, DraftManifest, DraftRevision, ErrorEnvelope } from "./part1";
import type { EvaluationCaseAdoptHistoryCommand, EvaluationCaseAdoptHistoryPayload, EvaluationCaseConfirmCommand, EvaluationCaseConfirmPayload, EvaluationCaseGenerateCandidateCommand, EvaluationCaseGenerateCandidatePayload, EvaluationCaseImportCommand, EvaluationCaseImportPayload, EvaluationCommand, EvaluationFixActionPayload, EvaluationFixApplyCommand, EvaluationFixProposeAllCommand, EvaluationFixProposeAllPayload, EvaluationFixProposeCommand, EvaluationFixProposePayload, EvaluationFixUndoCommand, EvaluationPayload, EvaluationQualityCommandResult, EvaluationRunActionPayload, EvaluationRunCancelCommand, EvaluationRunResult, EvaluationRunResumeCommand, EvaluationRunRetryCommand, EvaluationRunRetryPayload, EvaluationRunStartCommand, EvaluationRunStartPayload, EvaluationSuiteCreateCommand, EvaluationSuiteCreatePayload, EvaluationSuiteReviseCommand, EvaluationSuiteRevisePayload, Event, FileConnectorConfig, FixPlan, FreshnessPolicy, GoldenAssetRevision, GoldenAssetRevisionRecord, GoldenLineage, GraphEdge, GraphNode, GraphOntologyViewModel, ImportCommand, ImportPayload, InputContract, Invocation, InvocationStartCommand, InvocationStartPayload, InvocationStartResult, JobEvent, JobState, KnowledgeCitation, KnowledgeViewModel, LegacySkillManifestInput } from "./part2";
import type { ManifestInputSchema, ManifestProperty, McpConnectorConfig, MonitoringViewModel, NotReadyCommandResult, Operation, OutputContract, OwnerRef, PatchOperation, PermissionRef, PlanNode, PolicyCheck, PolicyGateEvaluateCommand, PolicyGateEvaluatePayload, ProfileField, ProfileRun, ProfileRunRecord, ProviderDocumentConfig, PublicationPublishCommand, PublicationPublishPayload, PublicationPublishResult, PublishedSkillConnectorConfig, PublishedSkillVersion, QueryPlan, RefreshRun, RefreshRunCommand, RefreshRunPayload, RefreshRunResult, ResourceCommand, ResourcePayload, ResourceRef, ResourceShareResult, RunProvenance, SaveManifestCommand, SaveManifestPayload, SchemaRef, Scope, SecretRef, SemanticViewModel, SkillAuthoringStartCommand, SkillAuthoringStartPayload, SkillAuthoringStartResult, SkillContract, SkillDependencies, SkillDraft, SkillDraftRetryCommand, SkillDraftRetryPayload, SkillDraftRevision, SkillDraftRunCommand, SkillDraftRunPayload, SkillDraftRunResult, SkillKind } from "./part3";
import type { SkillManifest, SkillManifestAction, SkillMetadata, SkillOperation, SkillPatch, SkillResult, SkillSpec, SkillViewManifest, SkillViewRevision, SkillViewShareGrant, SourceCleanCommand, SourceCleanPayload, SourceCleanResult, SourceGoldenConnectionCreateCommand, SourceGoldenConnectionCreatePayload, SourceGoldenConnectionResult, SourceGoldenIngestCommand, SourceGoldenIngestPayload, SourceGoldenIngestResult, SourceProfileCommand, SourceProfilePayload, SourceProfileResult, SourceRevision, SourceRevisionRecord, StorageRef, StreamCancelCommand, StreamCancelPayload, TypedPatch, ViewCell, ViewField, ViewIntent, WebConnectorConfig, frontend__server__knowledge_assets__contract_base__AnalysisKindSpec, frontend__server__knowledge_assets__contract_base__GraphOntologyKindSpec, frontend__server__knowledge_assets__contract_base__KnowledgeKindSpec, frontend__server__knowledge_assets__contract_base__MonitoringKindSpec, frontend__server__knowledge_assets__contract_base__SemanticKindSpec, frontend__server__knowledge_assets__contract_views__EvaluationCase, frontend__server__knowledge_assets__contract_views__EvaluationCaseResult, frontend__server__knowledge_assets__contract_views__EvaluationRun, frontend__server__knowledge_assets__contract_views__EvaluationSuite, frontend__server__knowledge_assets__contract_views__PolicyGateResult, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationCase, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationCaseResult, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationRun, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationSuite, frontend__server__knowledge_assets__evaluation_quality__models__PolicyGateResult, frontend__server__skill_authoring__models__AnalysisKindSpec, frontend__server__skill_authoring__models__GraphOntologyKindSpec, frontend__server__skill_authoring__models__KnowledgeKindSpec, frontend__server__skill_authoring__models__MonitoringKindSpec, frontend__server__skill_authoring__models__SemanticKindSpec } from "./part4";

export interface CoreContractBundle {
  sourceRevision?: SourceRevision | null;
  profileRun?: ProfileRun | null;
  cleaningRecipe?: CleaningRecipe | null;
  cleanRun?: CleanRun | null;
  goldenAssetRevision?: GoldenAssetRevision | null;
  skillDraftRevision?: SkillDraftRevision | null;
  skillResult?: SkillResult | null;
  viewIntent?: ViewIntent | null;
  viewModel?: DashboardViewModel | ChartViewModel | SemanticViewModel | KnowledgeViewModel | GraphOntologyViewModel | MonitoringViewModel | null;
  skillViewManifest?: SkillViewManifest | null;
  skillViewRevision?: SkillViewRevision | null;
  evaluationSuite?: frontend__server__knowledge_assets__contract_views__EvaluationSuite | null;
  evaluationRun?: frontend__server__knowledge_assets__contract_views__EvaluationRun | null;
  policyGateResult?: frontend__server__knowledge_assets__contract_views__PolicyGateResult | null;
  publishedSkillVersion?: PublishedSkillVersion | null;
  agentBinding?: AgentBinding | null;
  invocation?: Invocation | null;
  refreshRun?: RefreshRun | null;
  alertEvent?: AlertEvent | null;
  legacySkillManifestInput?: LegacySkillManifestInput | null;
  commandRequest?: CreateSkillDraftCommand | SaveManifestCommand | ResourceCommand | ConnectorCommand | ImportCommand | StreamCancelCommand | AssistantCommand | EvaluationCommand | EvaluationSuiteCreateCommand | EvaluationSuiteReviseCommand | EvaluationCaseImportCommand | EvaluationCaseAdoptHistoryCommand | EvaluationCaseGenerateCandidateCommand | EvaluationCaseConfirmCommand | EvaluationRunStartCommand | EvaluationRunCancelCommand | EvaluationRunResumeCommand | EvaluationRunRetryCommand | EvaluationFixProposeCommand | EvaluationFixProposeAllCommand | EvaluationFixApplyCommand | EvaluationFixUndoCommand | PolicyGateEvaluateCommand | ActionCommand | ArtifactExportCommand | SourceProfileCommand | SourceCleanCommand | SkillDraftRunCommand | SkillDraftRetryCommand | PublicationPublishCommand | RefreshRunCommand | InvocationStartCommand | SkillAuthoringStartCommand | SourceGoldenConnectionCreateCommand | SourceGoldenIngestCommand | null;
  commandResult?: DraftCommandResult | NotReadyCommandResult | SourceProfileResult | SourceCleanResult | SkillDraftRunResult | AssistantTurnResult | ArtifactExportResult | ResourceShareResult | PublicationPublishResult | RefreshRunResult | InvocationStartResult | EvaluationRunResult | EvaluationQualityCommandResult | SkillAuthoringStartResult | SourceGoldenConnectionResult | SourceGoldenIngestResult | null;
  commandResponse?: CommandResponse | null;
  operation?: Operation | null;
  event?: Event | null;
  audit?: Audit | null;
  jobState?: JobState | null;
  jobEvent?: JobEvent | null;
  connectorConfig?: FileConnectorConfig | ProviderDocumentConfig | DatabaseConnectorConfig | WebConnectorConfig | McpConnectorConfig | PublishedSkillConnectorConfig | null;
}
