/* Generated from contracts.py; do not edit manually. */

import type { ActionCommand, ActionUpdatePayload, AddCitationIntentPatch, AgentAnswer, AgentBinding, AgentEventEvidence, AgentExecutionEvidence, AgentToolCallEvidence, AlertEvent, ArtifactExportCommand, ArtifactExportPayload, ArtifactExportResult, ArtifactRef, AssetOwner, AssetPermission, AssistantCommand, AssistantContextEnvelope, AssistantDiff, AssistantTurnPayload, AssistantTurnResult, Audit, AuthoringErrorCode, AuthoringEvent, AuthoringOperation, AuthoringStatus, BigqueryConnectorConfig, Budget, BuildPlan, CapabilityReason, CaseCategory, CaseSource, ChartSeries, ChartViewModel, CleanRun, CleanRunRecord, CleaningRecipe, CleaningRecipeRecord, ClickhouseConnectorConfig, CommandResponse, CompatibilityTargets, ConnectionViewModel, ConnectorCommand, ConnectorOperation, ConnectorPayload, ContextRevisionRef, CreateSkillDraftCommand, CreateSkillDraftPayload, CsvConnectorConfig, CustomHttpConnectorConfig, DashboardChart, DashboardDrill, DashboardFilter, DashboardKpi, DashboardPresentationSpec, DashboardViewModel, DataAccessKindSpec, DiscoveredField, DiscoveredResource, DocumentConnectorConfig, DorisConnectorConfig, DraftCommandResult, DraftManifest, DraftRevision, ErrorEnvelope, EvaluationCaseAdoptHistoryCommand, EvaluationCaseAdoptHistoryPayload, EvaluationCaseConfirmCommand, EvaluationCaseConfirmPayload, EvaluationCaseGenerateCandidateCommand, EvaluationCaseGenerateCandidatePayload, EvaluationCaseImportCommand, EvaluationCaseImportPayload, EvaluationCommand, EvaluationFixActionPayload, EvaluationFixApplyCommand, EvaluationFixProposeAllCommand } from "./part1";
import type { EvaluationFixProposeAllPayload, EvaluationFixProposeCommand, EvaluationFixProposePayload, EvaluationFixUndoCommand, EvaluationPayload, EvaluationQualityCommandResult, EvaluationRunActionPayload, EvaluationRunCancelCommand, EvaluationRunResult, EvaluationRunResumeCommand, EvaluationRunRetryCommand, EvaluationRunRetryPayload, EvaluationRunStartCommand, EvaluationRunStartPayload, EvaluationSuiteCreateCommand, EvaluationSuiteCreatePayload, EvaluationSuiteReviseCommand, EvaluationSuiteRevisePayload, Event, ExcelConnectorConfig, FixPlan, FreshnessPolicy, GoldenAssetRevision, GoldenAssetRevisionRecord, GoldenLineage, GraphEdge, GraphNode, GraphOntologyViewModel, GraphRelationSpec, GraphqlConnectorConfig, HiveConnectorConfig, ImportCommand, ImportPayload, InputContract, Invocation, InvocationStartCommand, InvocationStartPayload, InvocationStartResult, JobEvent, JobState, JsonConnectorConfig, JsonValue, KafkaConnectorConfig, KnowledgeCitation, KnowledgeViewModel, LarkBaseConnectorConfig, LarkChatConnectorConfig, LarkDocConnectorConfig, LarkDriveConnectorConfig, LarkGroupConnectorConfig, LarkMailConnectorConfig, LarkMeetingConnectorConfig, LarkMinutesConnectorConfig, LarkSheetConnectorConfig, LarkWikiConnectorConfig, LegacySkillManifestInput, LocalFileConnectorConfig, ManifestInputSchema, ManifestProperty, McpCustomConnectorConfig, MonitoringInvocationView, MonitoringObservationView, MonitoringViewModel, MysqlConnectorConfig, NotReadyCommandResult, OpenapiSpecConnectorConfig, Operation, OracleConnectorConfig, OssConnectorConfig, OutputContract, OwnerRef, ParquetConnectorConfig, PatchImpact, PatchOperation, PatchProposal, PermissionRef } from "./part2";
import type { PlanNode, PolicyCheck, PolicyGateEvaluateCommand, PolicyGateEvaluatePayload, PostgresqlConnectorConfig, ProfileField, ProfileRun, ProfileRunRecord, PublicationPublishCommand, PublicationPublishPayload, PublicationPublishResult, PublishedSkillVersion, QueryPlan, RefreshRun, RefreshRunCommand, RefreshRunPayload, RefreshRunResult, ResourceCommand, ResourcePayload, ResourceRef, ResourceShareResult, RestApiConnectorConfig, RunProvenance, S3ConnectorConfig, SaveManifestCommand, SaveManifestPayload, SchemaRef, Scope, SecretRef, SemanticViewField, SemanticViewModel, SemanticViewRelationship, SetDashboardChartPatch, SetDashboardFilterPatch, SetDashboardKpiPatch, SetDescriptionPatch, SetGraphEntityPatch, SetGraphRelationPatch, SetPermissionScopePatch, SetQueryPlanPatch, SetRefreshPolicyPatch, SetSemanticDimensionPatch, SetSemanticMappingPatch, SetSemanticMetricPatch, SetSemanticRelationshipPatch, SetSopConditionPatch, SetSopStepPatch, SetSopToolRefPatch, SetThresholdPolicyPatch, SetTitlePatch, SkillAuthoringAnswerCommand, SkillAuthoringAnswerPayload, SkillAuthoringAnswerResult, SkillAuthoringExecuteCommand, SkillAuthoringExecutePayload, SkillAuthoringExecuteResult, SkillAuthoringPatchCommand, SkillAuthoringPatchPayload, SkillAuthoringPatchResult, SkillAuthoringStartCommand, SkillAuthoringStartPayload, SkillAuthoringStartResult, SkillContract, SkillDependencies, SkillDraft, SkillDraftRetryCommand, SkillDraftRetryPayload, SkillDraftRevision, SkillDraftRunCommand, SkillDraftRunPayload, SkillDraftRunResult, SkillKind, SkillManifest, SkillManifestAction, SkillMetadata, SkillOperation } from "./part3";
import type { SkillPatch, SkillResult, SkillSpec, SkillViewManifest, SkillViewRevision, SkillViewShareGrant, SnowflakeConnectorConfig, SopActionProposal, SopCondition, SopEvidenceRequirement, SopInputField, SopOutputField, SopPlanInput, SopPlanOutput, SopPlanStep, SopStep, SopStepEvidence, SopStepResult, SopToolRef, SopViewModel, SourceCleanCommand, SourceCleanPayload, SourceCleanResult, SourceGoldenConnectionCreateCommand, SourceGoldenConnectionCreatePayload, SourceGoldenConnectionResult, SourceGoldenIngestCommand, SourceGoldenIngestPayload, SourceGoldenIngestResult, SourceProfileCommand, SourceProfilePayload, SourceProfileResult, SourceRevision, SourceRevisionRecord, SqliteConnectorConfig, SqlserverConnectorConfig, StarrocksConnectorConfig, StorageRef, StreamCancelCommand, StreamCancelPayload, TemplateEvidenceRule, TemplateQualityGate, TemplateRef, TemplateSelection, TemplateSpec, TypedPatch, ViewCell, ViewField, ViewIntent, WebDiscoveryConnectorConfig, WebhookConnectorConfig, frontend__server__knowledge_assets__contract_base__AnalysisKindSpec, frontend__server__knowledge_assets__contract_base__GraphOntologyKindSpec, frontend__server__knowledge_assets__contract_base__KnowledgeKindSpec, frontend__server__knowledge_assets__contract_base__MonitoringKindSpec, frontend__server__knowledge_assets__contract_base__SemanticKindSpec, frontend__server__knowledge_assets__contract_base__SopKindSpec, frontend__server__knowledge_assets__contract_views__EvaluationCase, frontend__server__knowledge_assets__contract_views__EvaluationCaseResult, frontend__server__knowledge_assets__contract_views__EvaluationRun, frontend__server__knowledge_assets__contract_views__EvaluationSuite, frontend__server__knowledge_assets__contract_views__PolicyGateResult, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationCase, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationCaseResult, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationRun, frontend__server__knowledge_assets__evaluation_quality__models__EvaluationSuite, frontend__server__knowledge_assets__evaluation_quality__models__PolicyGateResult, frontend__server__skill_authoring__models__AnalysisKindSpec, frontend__server__skill_authoring__models__GraphOntologyKindSpec, frontend__server__skill_authoring__models__KnowledgeKindSpec, frontend__server__skill_authoring__models__MonitoringKindSpec, frontend__server__skill_authoring__models__SemanticKindSpec, frontend__server__skill_authoring__models__SopKindSpec } from "./part4";

export interface CoreContractBundle {
  sourceRevision?: SourceRevision | null;
  profileRun?: ProfileRun | null;
  cleaningRecipe?: CleaningRecipe | null;
  cleanRun?: CleanRun | null;
  goldenAssetRevision?: GoldenAssetRevision | null;
  skillDraftRevision?: SkillDraftRevision | null;
  skillResult?: SkillResult | null;
  viewIntent?: ViewIntent | null;
  viewModel?: DashboardViewModel | ChartViewModel | SemanticViewModel | KnowledgeViewModel | GraphOntologyViewModel | MonitoringViewModel | SopViewModel | null;
  skillViewManifest?: SkillViewManifest | null;
  skillViewRevision?: SkillViewRevision | null;
  evaluationSuite?: frontend__server__knowledge_assets__contract_views__EvaluationSuite | null;
  evaluationRun?: frontend__server__knowledge_assets__contract_views__EvaluationRun | null;
  policyGateResult?: frontend__server__knowledge_assets__contract_views__PolicyGateResult | null;
  publishedSkillVersion?: PublishedSkillVersion | null;
  agentBinding?: AgentBinding | null;
  invocation?: Invocation | null;
  refreshRun?: RefreshRun | null;
  alertEvent?: AlertEvent | null;
  legacySkillManifestInput?: LegacySkillManifestInput | null;
  commandRequest?: CreateSkillDraftCommand | SaveManifestCommand | ResourceCommand | ConnectorCommand | ImportCommand | StreamCancelCommand | AssistantCommand | EvaluationCommand | EvaluationSuiteCreateCommand | EvaluationSuiteReviseCommand | EvaluationCaseImportCommand | EvaluationCaseAdoptHistoryCommand | EvaluationCaseGenerateCandidateCommand | EvaluationCaseConfirmCommand | EvaluationRunStartCommand | EvaluationRunCancelCommand | EvaluationRunResumeCommand | EvaluationRunRetryCommand | EvaluationFixProposeCommand | EvaluationFixProposeAllCommand | EvaluationFixApplyCommand | EvaluationFixUndoCommand | PolicyGateEvaluateCommand | ActionCommand | ArtifactExportCommand | SourceProfileCommand | SourceCleanCommand | SkillDraftRunCommand | SkillDraftRetryCommand | PublicationPublishCommand | RefreshRunCommand | InvocationStartCommand | SkillAuthoringStartCommand | SkillAuthoringAnswerCommand | SkillAuthoringPatchCommand | SkillAuthoringExecuteCommand | SourceGoldenConnectionCreateCommand | SourceGoldenIngestCommand | null;
  commandResult?: DraftCommandResult | NotReadyCommandResult | SourceProfileResult | SourceCleanResult | SkillDraftRunResult | AssistantTurnResult | ArtifactExportResult | ResourceShareResult | PublicationPublishResult | RefreshRunResult | InvocationStartResult | EvaluationRunResult | EvaluationQualityCommandResult | SkillAuthoringStartResult | SkillAuthoringAnswerResult | SkillAuthoringPatchResult | SkillAuthoringExecuteResult | SourceGoldenConnectionResult | SourceGoldenIngestResult | null;
  commandResponse?: CommandResponse | null;
  operation?: Operation | null;
  event?: Event | null;
  audit?: Audit | null;
  jobState?: JobState | null;
  jobEvent?: JobEvent | null;
  connectorConfig?: LarkDocConnectorConfig | LarkWikiConnectorConfig | LarkDriveConnectorConfig | LarkMeetingConnectorConfig | LarkMinutesConnectorConfig | LarkGroupConnectorConfig | LarkChatConnectorConfig | LarkSheetConnectorConfig | LarkBaseConnectorConfig | LarkMailConnectorConfig | CsvConnectorConfig | ExcelConnectorConfig | JsonConnectorConfig | ParquetConnectorConfig | DocumentConnectorConfig | LocalFileConnectorConfig | S3ConnectorConfig | OssConnectorConfig | PostgresqlConnectorConfig | MysqlConnectorConfig | OracleConnectorConfig | SqlserverConnectorConfig | SqliteConnectorConfig | ClickhouseConnectorConfig | DorisConnectorConfig | StarrocksConnectorConfig | SnowflakeConnectorConfig | BigqueryConnectorConfig | HiveConnectorConfig | RestApiConnectorConfig | GraphqlConnectorConfig | WebDiscoveryConnectorConfig | WebhookConnectorConfig | KafkaConnectorConfig | McpCustomConnectorConfig | CustomHttpConnectorConfig | OpenapiSpecConnectorConfig | null;
  templateSpec?: TemplateSpec | null;
}
