"""Frozen inventories used by the v2.11.4.1 contract validator."""

CONNECTOR_IDS = {
    "bigquery",
    "clickhouse",
    "csv",
    "custom_http",
    "doc_txt",
    "doris",
    "excel",
    "graphql",
    "hive",
    "json",
    "kafka",
    "lark_base",
    "lark_chat",
    "lark_doc",
    "lark_drive",
    "lark_group",
    "lark_mail",
    "lark_meeting",
    "lark_minutes",
    "lark_sheet",
    "lark_wiki",
    "local_file",
    "mcp_custom",
    "mysql",
    "openapi_spec",
    "oracle",
    "oss",
    "parquet",
    "postgresql",
    "rest_api",
    "s3",
    "snowflake",
    "sqlserver",
    "sqlite",
    "starrocks",
    "web_discovery",
    "webhook",
}

REQUIRED_CERTIFICATION_SUBJECTS = {
    "csv",
    "doc_txt:html",
    "doc_txt:markdown",
    "doc_txt:pdf",
    "doc_txt:txt",
    "excel",
    "json",
    "lark_base",
    "lark_chat",
    "lark_doc",
    "lark_drive",
    "lark_group",
    "lark_meeting",
    "lark_minutes",
    "lark_sheet",
    "lark_wiki",
    "mysql",
    "openapi_spec",
    "oracle",
    "postgresql",
    "rest_api",
    "web_discovery",
}

E2E_CASE_IDS = {
    "E2E-BACKUP-RESTORE",
    "E2E-CONNECTOR-REQUIRED",
    "E2E-FRESH-INSTALL",
    "E2E-J1",
    "E2E-J2",
    "E2E-J3",
    "E2E-J4",
    "E2E-J5",
    "E2E-RESTART",
    "E2E-SECRET-ROTATION",
    "E2E-TENANT-ISOLATION",
    "E2E-UPGRADE-ROLLBACK",
    "E2E-WORKER-CRASH",
}

GA_GATE_IDS = {
    "availability",
    "backup-restore-rpo-rto",
    "capacity-and-latency",
    "captures-13-png-12",
    "commercial-ga",
    "data-governance-audit",
    "five-product-journeys",
    "fresh-install",
    "frozen-identity",
    "gm-01-through-gm-20-contract",
    "loc-package-hotspots",
    "mandatory-connectors",
    "observability-alerts",
    "production-fixture-isolation",
    "restart-and-worker-crash",
    "route-manifests-all-nodes",
    "secret-rotation",
    "single-production-ui",
    "source-provenance-47",
    "supply-chain-security",
    "tenant-isolation",
    "upgrade-rollback",
    "visual-interaction-a11y",
}

STEP_1_PASS_GATES = {
    "captures-13-png-12",
    "frozen-identity",
    "gm-01-through-gm-20-contract",
    "loc-package-hotspots",
    "route-manifests-all-nodes",
    "source-provenance-47",
}
