CREATE TABLE ads_trd_finance_combine_shell_info_1d_di (
  app_type_code STRING,
  finance_custom_income_type_desc STRING,
  asset_type_desc STRING,
  mean_type_desc STRING,
  business_type_desc STRING,
  scene_desc STRING,
  consume_unt_1d BIGINT,
  consume_cnt_1d BIGINT,
  consume_amt_1d DOUBLE,
  cost_amt_1d DOUBLE,
  subsidy_amt_1d DOUBLE,
  system_give_amt_1d DOUBLE,
  system_give_tebean_amt_1d DOUBLE,
  system_give_gift_amt_1d DOUBLE,
  system_give_prop_amt_1d DOUBLE,
  system_give_daibi_amt_1d DOUBLE,
  return_cnt_1d BIGINT,
  return_amt_1d DOUBLE,
  return_cost_amt_1d DOUBLE,
  return_subsidy_amt_1d DOUBLE,
  revenue_amt_1d DOUBLE,
  cost_revenue_amt_1d DOUBLE,
  subsidy_revenue_amt_1d DOUBLE,
  personal_income_amt_1d DOUBLE,
  profit_amt_1d DOUBLE,
  dt DATE
);
